league: EPL

model:
  voting: #Percentage of long term form and short term form perencage. Total should add up to 1
    form_longterm_percentage: 0.7
    form_shortterm_percentage: 0.3
  matchdays_to_drop: 4
  regressor: PoissonRegressor #One of the available [LinearRegression, PoissonRegressor, SVR]

bettor:
  initial_bank: 60
  kelly_cap: 0.05 #The max percentage of the current bankroll to bet

data_gathering:
  long_term_form: null # Months of long_form, null indicates season long form
  short_term_form: 3 # Months of short-term form
  seasons_to_gather: ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024'] 
  # List of the seasons to gather for the model to be trained on. 
  # Subset of ['2017', '2018', '2019', '2020', '2021', '2022', '2023', '2024']
  current_season: '2024'
  paths:
    EPL: 
      data_co_uk_path: 'eplprediction/data/DataCoUkFiles/'
      evaluation_output: 'eplprediction/data/evaluation/'
      database: 'eplprediction/database/EPL_database.db'
  bookmaker: 
    EPL: 
      url: 'https://en.stoiximan.gr/sport/soccer/england/premier-league/1/' 
      dictionary_path: 'eplprediction/data/dictionaries/bookmaker.yaml'
  data_co_uk: 
    EPL:  
      url: 'https://www.football-data.co.uk/mmz4281/2425/E0.csv' #For the current season dataload
      dictionary_path: 'eplprediction/data/dictionaries/data_co_uk.yaml'
  fixture_download:
    EPL:
      url: 'https://fixturedownload.com/download/epl-2024-GMTStandardTime.csv'
      dictionary_path: 'eplprediction/data/dictionaries/fixture_download.yaml'